#![forbid(unsafe_code)]

//! Progress bar widget.

use crate::block::Block;
use crate::{
    MeasurableWidget, SizeConstraints, Widget, apply_style, clear_text_area, clear_text_row,
};
use ftui_core::geometry::{Rect, Size};
use ftui_render::cell::{Cell, PackedRgba};
use ftui_render::frame::{Frame, HitId, HitRegion};
use ftui_style::Style;
use ftui_text::display_width;

/// Hit region tag for the pause button on a progress bar.
pub const PROGRESS_HIT_PAUSE: HitRegion = HitRegion::Custom(11);
/// Hit region tag for the cancel button on a progress bar.
pub const PROGRESS_HIT_CANCEL: HitRegion = HitRegion::Custom(12);

/// Whether the progress bar is determinate (known progress) or indeterminate (marquee).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProgressBarMode {
    /// Known progress ratio (0.0 ..= 1.0).  The bar shows a filled portion.
    Determinate,
    /// Unknown duration — the bar shows a sliding marquee segment.
    Indeterminate,
}

impl Default for ProgressBarMode {
    fn default() -> Self {
        Self::Determinate
    }
}

/// A widget to display a progress bar.
///
/// # Modes
///
/// - **Determinate**: use [`ProgressBar::determinate`] with `current / total` to show exact
///   progress.  The bar fills proportionally and an optional auto-label can show the percentage.
/// - **Indeterminate**: use [`ProgressBar::indeterminate`] to show a sliding marquee segment
///   for operations with unknown duration.  The caller advances [`marquee_offset`] each tick.
///
/// # Pause / Cancel
///
/// When a [`HitId`] is assigned and [`show_pause`] / [`show_cancel`] is set, the bar renders
/// small clickable targets at the right edge and registers hit regions tagged with
/// [`PROGRESS_HIT_PAUSE`] / [`PROGRESS_HIT_CANCEL`].
///
/// # Accessibility
///
/// Set [`reduced_motion(true)`] to replace the marquee animation with a static centered
/// segment, respecting the user's motion preferences.
///
/// [`marquee_offset`]: Self::marquee_offset
/// [`show_pause`]: Self::show_pause
/// [`show_cancel`]: Self::show_cancel
/// [`reduced_motion(true)`]: Self::reduced_motion
#[derive(Debug, Clone)]
pub struct ProgressBar<'a> {
    block: Option<Block<'a>>,
    ratio: f64,
    mode: ProgressBarMode,
    current: Option<u64>,
    total: Option<u64>,
    label: Option<&'a str>,
    auto_label: bool,
    marquee_offset: u16,
    marquee_segment_width: Option<u16>,
    style: Style,
    gauge_style: Style,
    hit_id: Option<HitId>,
    show_pause: bool,
    show_cancel: bool,
    reduced_motion: bool,
}

impl Default for ProgressBar<'_> {
    fn default() -> Self {
        Self {
            block: None,
            ratio: 0.0,
            mode: ProgressBarMode::Determinate,
            current: None,
            total: None,
            label: None,
            auto_label: false,
            marquee_offset: 0,
            marquee_segment_width: None,
            style: Style::default(),
            gauge_style: Style::default(),
            hit_id: None,
            show_pause: false,
            show_cancel: false,
            reduced_motion: false,
        }
    }
}

impl<'a> ProgressBar<'a> {
    /// Create a new progress bar with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the surrounding block.
    #[must_use]
    pub fn block(mut self, block: Block<'a>) -> Self {
        self.block = Some(block);
        self
    }

    /// Set the progress ratio (clamped to 0.0..=1.0).
    ///
    /// Note: this is overridden by [`determinate`] which computes the ratio from
    /// `current / total`.
    ///
    /// [`determinate`]: Self::determinate
    #[must_use]
    pub fn ratio(mut self, ratio: f64) -> Self {
        self.ratio = if ratio.is_nan() {
            0.0
        } else {
            ratio.clamp(0.0, 1.0)
        };
        self
    }

    /// Set the centered label text.
    ///
    /// If a label is set here it takes priority over the auto-label generated by
    /// [`auto_label`].
    ///
    /// [`auto_label`]: Self::auto_label
    #[must_use]
    pub fn label(mut self, label: &'a str) -> Self {
        self.label = Some(label);
        self
    }

    /// Set the base style.
    #[must_use]
    pub fn style(mut self, style: Style) -> Self {
        self.style = style;
        self
    }

    /// Set the filled portion style.
    #[must_use]
    pub fn gauge_style(mut self, style: Style) -> Self {
        self.gauge_style = style;
        self
    }

    // ------------------------------------------------------------------
    // New builder methods
    // ------------------------------------------------------------------

    /// Switch to **determinate** mode with a known `current` / `total`.
    ///
    /// The ratio is computed as `current / total` (clamped to `0.0 ..= 1.0`).
    /// Auto-label is enabled so that a percentage text is shown when no
    /// explicit [`label`] is set.
    ///
    /// # Panics
    ///
    /// Panics if `total == 0`.
    ///
    /// [`label`]: Self::label
    #[must_use]
    pub fn determinate(mut self, current: u64, total: u64) -> Self {
        assert!(total > 0, "ProgressBar::determinate: total must be > 0");
        self.current = Some(current);
        self.total = Some(total);
        self.ratio = (current as f64 / total as f64).clamp(0.0, 1.0);
        self.mode = ProgressBarMode::Determinate;
        self.auto_label = true;
        self
    }

    /// Switch to **indeterminate** mode (marquee animation).
    ///
    /// The bar shows a sliding segment whose position is controlled by
    /// [`marquee_offset`].  Advance `marquee_offset` by 1 (or more) each
    /// frame to animate.
    ///
    /// [`marquee_offset`]: Self::marquee_offset
    #[must_use]
    pub fn indeterminate(mut self) -> Self {
        self.mode = ProgressBarMode::Indeterminate;
        self
    }

    /// Set the marquee animation offset (in cells).
    ///
    /// Only meaningful in indeterminate mode.  The offset wraps at the bar's
    /// rendered width.
    #[must_use]
    pub fn marquee_offset(mut self, offset: u16) -> Self {
        self.marquee_offset = offset;
        self
    }

    /// Override the marquee segment width (in cells).
    ///
    /// When unset the segment defaults to `max(1, width / 3)`.
    #[must_use]
    pub fn marquee_segment_width(mut self, width: u16) -> Self {
        self.marquee_segment_width = Some(width);
        self
    }

    /// Enable or disable the auto-generated label.
    ///
    /// When enabled (and no explicit [`label`] is set), the bar renders a
    /// percentage string such as `"60%"` (determinate) or `"..."` (indeterminate).
    ///
    /// [`label`]: Self::label
    #[must_use]
    pub fn auto_label(mut self, enable: bool) -> Self {
        self.auto_label = enable;
        self
    }

    /// Assign a hit-testing ID for interactive regions.
    ///
    /// When set, pause and cancel buttons can register hit regions for mouse
    /// interaction.
    #[must_use]
    pub fn hit_id(mut self, id: HitId) -> Self {
        self.hit_id = Some(id);
        self
    }

    /// Show a pause button (hit region [`PROGRESS_HIT_PAUSE`]) at the right edge
    /// of the bar.
    ///
    /// Requires a [`hit_id`] to be set.
    ///
    /// [`hit_id`]: Self::hit_id
    #[must_use]
    pub fn show_pause(mut self, show: bool) -> Self {
        self.show_pause = show;
        self
    }

    /// Show a cancel button (hit region [`PROGRESS_HIT_CANCEL`]) at the right edge
    /// of the bar.
    ///
    /// Requires a [`hit_id`] to be set.
    ///
    /// [`hit_id`]: Self::hit_id
    #[must_use]
    pub fn show_cancel(mut self, show: bool) -> Self {
        self.show_cancel = show;
        self
    }

    /// Enable or disable reduced-motion mode.
    ///
    /// When enabled, the indeterminate marquee collapses to a static centred
    /// segment instead of animating.
    #[must_use]
    pub fn reduced_motion(mut self, enable: bool) -> Self {
        self.reduced_motion = enable;
        self
    }

    // ------------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------------

    /// Generate the auto-label text when `auto_label` is true and no explicit
    /// label was provided.
    fn auto_label_text(&self) -> Option<String> {
        if !self.auto_label {
            return None;
        }
        match self.mode {
            ProgressBarMode::Determinate => {
                match (self.current, self.total) {
                    (Some(c), Some(t)) => {
                        let pct = (self.ratio * 100.0).round() as u8;
                        Some(format!("{c}/{t} ({pct}%)"))
                    }
                    _ => {
                        let pct = (self.ratio * 100.0).round() as u8;
                        Some(format!("{pct}%"))
                    }
                }
            }
            ProgressBarMode::Indeterminate => Some("...".to_owned()),
        }
    }

    /// Return the text to display (explicit label, or auto-label, or None).
    fn effective_label(&self) -> Option<String> {
        self.label
            .map(|s| s.to_owned())
            .or_else(|| self.auto_label_text())
    }

    /// Draw the filled / gauge portion for determinate mode.
    fn draw_bar_filled(&self, bar_area: Rect, frame: &mut Frame, filled_width: u16) {
        let deg = frame.buffer.degradation;
        let gauge_style = if deg.apply_styling() {
            self.gauge_style
        } else {
            Style::default()
        };
        let fill_char = if deg.apply_styling() { ' ' } else { '#' };

        for y in bar_area.top()..bar_area.bottom() {
            for x in 0..filled_width {
                let cell_x = bar_area.left().saturating_add(x);
                if cell_x < bar_area.right() {
                    let mut cell = Cell::from_char(fill_char);
                    apply_style(&mut cell, gauge_style);
                    frame.buffer.set_fast(cell_x, y, cell);
                }
            }
        }
    }

    /// Draw the marquee segment for indeterminate mode.
    fn draw_marquee(&self, bar_area: Rect, frame: &mut Frame) {
        let total_width = bar_area.width;
        if total_width == 0 {
            return;
        }

        let deg = frame.buffer.degradation;
        let gauge_style = if deg.apply_styling() {
            self.gauge_style
        } else {
            Style::default()
        };
        let fill_char = if deg.apply_styling() { ' ' } else { '#' };

        let seg_width = self
            .marquee_segment_width
            .unwrap_or_else(|| (total_width / 3).max(1))
            .min(total_width);

        let base_offset = if self.reduced_motion {
            // Static centred segment
            (total_width - seg_width) / 2
        } else {
            self.marquee_offset % total_width
        };

        for y in bar_area.top()..bar_area.bottom() {
            for i in 0..seg_width {
                let cell_x = bar_area.left().saturating_add((base_offset + i) % total_width);
                if cell_x < bar_area.right() {
                    let mut cell = Cell::from_char(fill_char);
                    apply_style(&mut cell, gauge_style);
                    frame.buffer.set_fast(cell_x, y, cell);
                }
            }
        }
    }

    /// Render pause / cancel hit regions and their visual indicators.
    fn render_hit_regions(&self, area: Rect, frame: &mut Frame) {
        let Some(hit_id) = self.hit_id else {
            return;
        };

        let has_buttons = self.show_pause || self.show_cancel;
        if !has_buttons {
            return;
        }

        let mut btn_x = area.right();
        let deg = frame.buffer.degradation;
        let btn_style = if deg.apply_styling() {
            self.style
        } else {
            Style::default()
        };

        if self.show_cancel {
            btn_x = btn_x.saturating_sub(1);
            if btn_x >= area.left() {
                let mut cell = Cell::from_char('X');
                apply_style(&mut cell, btn_style);
                frame.buffer.set_fast(btn_x, area.y, cell);
                frame.register_hit(
                    Rect::new(btn_x, area.y, 1, area.height),
                    hit_id,
                    PROGRESS_HIT_CANCEL,
                    1,
                );
            }
        }

        if self.show_pause {
            let avail = btn_x.saturating_sub(area.left());
            if avail >= 2 {
                btn_x = btn_x.saturating_sub(2);
                crate::draw_text_span(frame, btn_x, area.y, "||", btn_style, area.right());
                frame.register_hit(
                    Rect::new(btn_x, area.y, 2.min(avail), area.height),
                    hit_id,
                    PROGRESS_HIT_PAUSE,
                    0,
                );
            } else if avail == 1 {
                btn_x = btn_x.saturating_sub(1);
                let mut cell = Cell::from_char('|');
                apply_style(&mut cell, btn_style);
                frame.buffer.set_fast(btn_x, area.y, cell);
                frame.register_hit(
                    Rect::new(btn_x, area.y, 1, area.height),
                    hit_id,
                    PROGRESS_HIT_PAUSE,
                    0,
                );
            }
        }
    }
}

impl<'a> Widget for ProgressBar<'a> {
    fn render(&self, area: Rect, frame: &mut Frame) {
        #[cfg(feature = "tracing")]
        let _span = tracing::debug_span!(
            "widget_render",
            widget = "ProgressBar",
            x = area.x,
            y = area.y,
            w = area.width,
            h = area.height
        )
        .entered();

        let deg = frame.buffer.degradation;

        // Skeleton+: skip entirely
        if !deg.render_content() {
            return;
        }

        // EssentialOnly: just show percentage / status text, no bar
        if !deg.render_decorative() {
            clear_text_area(frame, area, Style::default());
            let display_text = self.effective_label().unwrap_or_else(|| {
                let pct = format!("{}%", (self.ratio * 100.0) as u8);
                pct
            });
            crate::draw_text_span(
                frame,
                area.x,
                area.y,
                &display_text,
                Style::default(),
                area.right(),
            );
            return;
        }

        let base_style = if deg.apply_styling() {
            self.style
        } else {
            Style::default()
        };

        clear_text_area(frame, area, base_style);

        let bar_area = match &self.block {
            Some(b) => {
                b.render(area, frame);
                b.inner(area)
            }
            None => area,
        };

        if bar_area.is_empty() {
            return;
        }

        // Reserve space at the right for pause/cancel buttons if applicable.
        let mut button_reserve: u16 = 0;
        if self.hit_id.is_some() && (self.show_pause || self.show_cancel) {
            if self.show_cancel {
                button_reserve = button_reserve.saturating_add(1);
            }
            if self.show_pause {
                button_reserve = button_reserve.saturating_add(2);
            }
        }

        let bar_content_width = if button_reserve >= bar_area.width {
            0
        } else {
            bar_area.width.saturating_sub(button_reserve)
        };

        let content_area = Rect::new(bar_area.x, bar_area.y, bar_content_width, bar_area.height);

        if content_area.width > 0 {
            match self.mode {
                ProgressBarMode::Determinate => {
                    let max_width = content_area.width as f64;
                    let filled_width = if self.ratio >= 1.0 {
                        content_area.width
                    } else {
                        (max_width * self.ratio).floor() as u16
                    };
                    self.draw_bar_filled(content_area, frame, filled_width);
                }
                ProgressBarMode::Indeterminate => {
                    self.draw_marquee(content_area, frame);
                }
            }
        }

        // Draw label (centered within the overall bar area)
        let label_style = if deg.apply_styling() {
            self.style
        } else {
            Style::default()
        };
        if let Some(label) = self.effective_label() {
            let label_width = display_width(&label);
            let label_x = bar_area
                .left()
                .saturating_add(((bar_area.width as usize).saturating_sub(label_width) / 2) as u16);
            let label_y = bar_area.top().saturating_add(bar_area.height / 2);

            crate::draw_text_span(
                frame,
                label_x,
                label_y,
                &label,
                label_style,
                bar_area.right(),
            );
        }

        // Render pause/cancel buttons and hit regions
        if self.hit_id.is_some() && (self.show_pause || self.show_cancel) {
            self.render_hit_regions(bar_area, frame);
        }
    }
}

impl MeasurableWidget for ProgressBar<'_> {
    fn measure(&self, _available: Size) -> SizeConstraints {
        // ProgressBar fills available width, has fixed height of 1 (or block inner height)
        let (block_width, block_height) = self
            .block
            .as_ref()
            .map(|b| {
                let inner = b.inner(Rect::new(0, 0, 100, 100));
                let w_overhead = 100u16.saturating_sub(inner.width);
                let h_overhead = 100u16.saturating_sub(inner.height);
                (w_overhead, h_overhead)
            })
            .unwrap_or((0, 0));

        // Minimum: 1 cell for bar + block overhead
        let min_width = 1u16.saturating_add(block_width);
        let min_height = 1u16.saturating_add(block_height);

        SizeConstraints {
            min: Size::new(min_width, min_height),
            preferred: Size::new(min_width, min_height), // Fills width, so preferred = min
            max: None, // Can grow to fill available space
        }
    }

    fn has_intrinsic_size(&self) -> bool {
        true
    }
}

// ---------------------------------------------------------------------------
// Accessibility
// ---------------------------------------------------------------------------

impl ftui_a11y::Accessible for ProgressBar<'_> {
    fn accessibility_nodes(&self, area: Rect) -> Vec<ftui_a11y::node::A11yNodeInfo> {
        use ftui_a11y::node::{A11yNodeInfo, A11yRole, A11yState};

        let id = crate::a11y_node_id(area);
        let display_text = self.effective_label().unwrap_or_else(|| {
            if self.mode == ProgressBarMode::Indeterminate {
                "...".to_owned()
            } else {
                let pct = (self.ratio * 100.0).round() as u32;
                format!("{pct}%")
            }
        });

        let state = if self.mode == ProgressBarMode::Indeterminate {
            A11yState {
                busy: true,
                value_text: Some(display_text.clone()),
                ..A11yState::default()
            }
        } else {
            A11yState {
                value_now: Some(self.ratio),
                value_min: Some(0.0),
                value_max: Some(1.0),
                value_text: Some(display_text.clone()),
                ..A11yState::default()
            }
        };

        vec![
            A11yNodeInfo::new(id, A11yRole::ProgressBar, area)
                .with_name(display_text)
                .with_state(state),
        ]
    }
}

// ---------------------------------------------------------------------------
// ProgressBarGroup
// ---------------------------------------------------------------------------

/// A single item within a [`ProgressBarGroup`].
#[derive(Debug, Clone)]
pub struct ProgressBarGroupItem<'a> {
    /// Human-readable label displayed above or beside the bar.
    pub label: &'a str,
    /// Short status text shown on the right side of the label line.
    pub status: Option<&'a str>,
    /// The progress bar configuration.
    pub bar: ProgressBar<'a>,
}

impl<'a> ProgressBarGroupItem<'a> {
    /// Create a new group item with a label and a progress bar.
    pub fn new(label: &'a str, bar: ProgressBar<'a>) -> Self {
        Self {
            label,
            status: None,
            bar,
        }
    }

    /// Set the status text.
    #[must_use]
    pub fn status(mut self, status: &'a str) -> Self {
        self.status = Some(status);
        self
    }
}

/// A panel that renders multiple [`ProgressBarGroupItem`]s stacked vertically.
///
/// Each item renders as:
///
/// ```text
/// Label text                                         [Status]
/// [======================== bar ========================]
/// ```
#[derive(Debug, Clone)]
pub struct ProgressBarGroup<'a> {
    items: Vec<ProgressBarGroupItem<'a>>,
    style: Style,
    spacing: u16,
    block: Option<Block<'a>>,
}

impl<'a> ProgressBarGroup<'a> {
    /// Create an empty group.
    pub fn new() -> Self {
        Self {
            items: Vec::new(),
            style: Style::default(),
            spacing: 0,
            block: None,
        }
    }

    /// Add an item to the group.
    #[must_use]
    pub fn add(mut self, item: ProgressBarGroupItem<'a>) -> Self {
        self.items.push(item);
        self
    }

    /// Set the base style.
    #[must_use]
    pub fn style(mut self, style: Style) -> Self {
        self.style = style;
        self
    }

    /// Set vertical spacing (in rows) between items.
    #[must_use]
    pub fn spacing(mut self, spacing: u16) -> Self {
        self.spacing = spacing;
        self
    }

    /// Wrap the group in a [`Block`] container.
    #[must_use]
    pub fn block(mut self, block: Block<'a>) -> Self {
        self.block = Some(block);
        self
    }
}

impl Default for ProgressBarGroup<'_> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'a> Widget for ProgressBarGroup<'a> {
    fn render(&self, area: Rect, frame: &mut Frame) {
        #[cfg(feature = "tracing")]
        let _span = tracing::debug_span!(
            "widget_render",
            widget = "ProgressBarGroup",
            x = area.x,
            y = area.y,
            w = area.width,
            h = area.height
        )
        .entered();

        let deg = frame.buffer.degradation;
        if !deg.render_content() {
            return;
        }

        let base_style = if deg.apply_styling() {
            self.style
        } else {
            Style::default()
        };

        let inner_area = match &self.block {
            Some(b) => {
                b.render(area, frame);
                b.inner(area)
            }
            None => area,
        };

        if inner_area.is_empty() || self.items.is_empty() {
            return;
        }

        // Each item uses 2 rows: one for label+status, one for the bar
        // Plus spacing between items (but not after the last)
        let rows_per_item = 2u16.saturating_add(self.spacing);
        let total_rows = self
            .items
            .len()
            .saturating_mul(rows_per_item as usize)
            .saturating_sub(self.spacing as usize); // no spacing after last
        if total_rows == 0 {
            return;
        }

        let mut y = inner_area.y;
        let max_y = inner_area.bottom();

        for (i, item) in self.items.iter().enumerate() {
            if y >= max_y {
                break;
            }

            let bar_row = y;

            let label_width = display_width(item.label);
            let status_width = item.status.map_or(0, display_width);

            let bar_area = Rect::new(inner_area.x, bar_row, inner_area.width, 1);

            // Draw the label text at the left
            if label_width > 0 && deg.render_decorative() {
                crate::draw_text_span(
                    frame,
                    bar_area.x,
                    bar_row,
                    item.label,
                    base_style,
                    bar_area.right(),
                );
            }

            // Draw the progress bar
            item.bar.render(bar_area, frame);

            // Draw status text at the right
            if let Some(status) = item.status {
                if deg.render_decorative() {
                    let status_x = bar_area.right().saturating_sub(status_width as u16);
                    if status_x > bar_area.x.saturating_add(label_width as u16) {
                        crate::draw_text_span(
                            frame,
                            status_x,
                            bar_row,
                            status,
                            base_style,
                            bar_area.right(),
                        );
                    }
                }
            }

            y = y.saturating_add(1); // bar row

            // Spacing between items (not after the last)
            if i + 1 < self.items.len() {
                y = y.saturating_add(self.spacing);
            }
        }
    }
}

impl MeasurableWidget for ProgressBarGroup<'_> {
    fn measure(&self, _available: Size) -> SizeConstraints {
        let rows_per_item = 2u16.saturating_add(self.spacing);
        let total_rows = self
            .items
            .len()
            .saturating_mul(rows_per_item as usize)
            .saturating_sub(self.spacing as usize);

        let (block_width, block_height) = self
            .block
            .as_ref()
            .map(|b| {
                let inner = b.inner(Rect::new(0, 0, 100, 100));
                let w_overhead = 100u16.saturating_sub(inner.width);
                let h_overhead = 100u16.saturating_sub(inner.height);
                (w_overhead, h_overhead)
            })
            .unwrap_or((0, 0));

        let min_width = 1u16.saturating_add(block_width);
        let min_height = (total_rows as u16).saturating_add(block_height);

        SizeConstraints {
            min: Size::new(min_width, min_height),
            preferred: Size::new(min_width, min_height),
            max: None,
        }
    }

    fn has_intrinsic_size(&self) -> bool {
        true
    }
}

impl ftui_a11y::Accessible for ProgressBarGroup<'_> {
    fn accessibility_nodes(&self, area: Rect) -> Vec<ftui_a11y::node::A11yNodeInfo> {
        use ftui_a11y::node::{A11yNodeInfo, A11yRole, A11yState};

        let id = crate::a11y_node_id(area);
        let names: Vec<&str> = self.items.iter().map(|i| i.label).collect();
        let name = names.join(", ");

        vec![A11yNodeInfo::new(id, A11yRole::Group, area).with_name(name)]
    }
}

// ---------------------------------------------------------------------------
// MiniBar
// ---------------------------------------------------------------------------

/// Color thresholds for [`MiniBar`].
#[derive(Debug, Clone, Copy)]
pub struct MiniBarColors {
    pub high: PackedRgba,
    pub mid: PackedRgba,
    pub low: PackedRgba,
    pub critical: PackedRgba,
}

impl MiniBarColors {
    pub fn new(high: PackedRgba, mid: PackedRgba, low: PackedRgba, critical: PackedRgba) -> Self {
        Self {
            high,
            mid,
            low,
            critical,
        }
    }
}

impl Default for MiniBarColors {
    fn default() -> Self {
        Self {
            high: PackedRgba::rgb(64, 200, 120),
            mid: PackedRgba::rgb(255, 180, 64),
            low: PackedRgba::rgb(80, 200, 240),
            critical: PackedRgba::rgb(160, 160, 160),
        }
    }
}

/// Thresholds for mapping values to colors.
#[derive(Debug, Clone, Copy)]
pub struct MiniBarThresholds {
    pub high: f64,
    pub mid: f64,
    pub low: f64,
}

impl Default for MiniBarThresholds {
    fn default() -> Self {
        Self {
            high: 0.75,
            mid: 0.50,
            low: 0.25,
        }
    }
}

/// Compact progress indicator for dashboard-style metrics.
#[derive(Debug, Clone)]
pub struct MiniBar {
    value: f64,
    width: u16,
    show_percent: bool,
    style: Style,
    filled_char: char,
    empty_char: char,
    colors: MiniBarColors,
    thresholds: MiniBarThresholds,
}

impl MiniBar {
    /// Create a new MiniBar with value in the 0.0..=1.0 range.
    pub fn new(value: f64, width: u16) -> Self {
        Self {
            value,
            width,
            show_percent: false,
            style: Style::new(),
            filled_char: '█',
            empty_char: '░',
            colors: MiniBarColors::default(),
            thresholds: MiniBarThresholds::default(),
        }
    }

    /// Override the value (clamped to 0.0..=1.0).
    #[must_use]
    pub fn value(mut self, value: f64) -> Self {
        self.value = value;
        self
    }

    /// Override the displayed width.
    #[must_use]
    pub fn width(mut self, width: u16) -> Self {
        self.width = width;
        self
    }

    /// Enable or disable percentage text.
    #[must_use]
    pub fn show_percent(mut self, show: bool) -> Self {
        self.show_percent = show;
        self
    }

    /// Set the base style for the bar.
    #[must_use]
    pub fn style(mut self, style: Style) -> Self {
        self.style = style;
        self
    }

    /// Override the filled block character.
    #[must_use]
    pub fn filled_char(mut self, ch: char) -> Self {
        self.filled_char = ch;
        self
    }

    /// Override the empty block character.
    #[must_use]
    pub fn empty_char(mut self, ch: char) -> Self {
        self.empty_char = ch;
        self
    }

    /// Override the color thresholds.
    #[must_use]
    pub fn thresholds(mut self, thresholds: MiniBarThresholds) -> Self {
        self.thresholds = thresholds;
        self
    }

    /// Override the color palette.
    #[must_use]
    pub fn colors(mut self, colors: MiniBarColors) -> Self {
        self.colors = colors;
        self
    }

    /// Map a value to a color using default thresholds.
    pub fn color_for_value(value: f64) -> PackedRgba {
        let v = if value.is_finite() { value } else { 0.0 };
        let v = v.clamp(0.0, 1.0);
        let thresholds = MiniBarThresholds::default();
        let colors = MiniBarColors::default();
        if v > thresholds.high {
            colors.high
        } else if v > thresholds.mid {
            colors.mid
        } else if v > thresholds.low {
            colors.low
        } else {
            colors.critical
        }
    }

    /// Render the bar as a string (for testing/debugging).
    pub fn render_string(&self) -> String {
        let width = self.width as usize;
        if width == 0 {
            return String::new();
        }
        let filled = self.filled_cells(width);
        let empty = width.saturating_sub(filled);
        let mut out = String::with_capacity(width);
        out.extend(std::iter::repeat_n(self.filled_char, filled));
        out.extend(std::iter::repeat_n(self.empty_char, empty));
        out
    }

    fn normalized_value(&self) -> f64 {
        if self.value.is_finite() {
            self.value.clamp(0.0, 1.0)
        } else {
            0.0
        }
    }

    fn filled_cells(&self, width: usize) -> usize {
        if width == 0 {
            return 0;
        }
        let v = self.normalized_value();
        let filled = (v * width as f64).round() as usize;
        filled.min(width)
    }

    fn color_for_value_with_palette(&self, value: f64) -> PackedRgba {
        let v = if value.is_finite() { value } else { 0.0 };
        let v = v.clamp(0.0, 1.0);
        if v > self.thresholds.high {
            self.colors.high
        } else if v > self.thresholds.mid {
            self.colors.mid
        } else if v > self.thresholds.low {
            self.colors.low
        } else {
            self.colors.critical
        }
    }
}

impl Widget for MiniBar {
    fn render(&self, area: Rect, frame: &mut Frame) {
        #[cfg(feature = "tracing")]
        let _span = tracing::debug_span!(
            "widget_render",
            widget = "MiniBar",
            x = area.x,
            y = area.y,
            w = area.width,
            h = area.height
        )
        .entered();

        if area.is_empty() {
            return;
        }

        let deg = frame.buffer.degradation;
        if !deg.render_content() {
            return;
        }

        let base_style = if deg.apply_styling() {
            self.style
        } else {
            Style::default()
        };
        clear_text_row(frame, area, base_style);

        let value = self.normalized_value();

        if !deg.render_decorative() {
            if self.show_percent {
                let pct = format!("{:3.0}%", value * 100.0);
                let pct_width = display_width(&pct) as u16;
                if area.width >= pct_width {
                    let text_x = area.right().saturating_sub(pct_width);
                    crate::draw_text_span(
                        frame,
                        text_x,
                        area.y,
                        &pct,
                        Style::default(),
                        area.right(),
                    );
                } else {
                    crate::draw_text_span(
                        frame,
                        area.x,
                        area.y,
                        pct.trim_start(),
                        Style::default(),
                        area.right(),
                    );
                }
            }
            return;
        }

        let mut bar_width = self.width.min(area.width) as usize;
        let mut render_percent = false;
        let mut percent_text = String::new();
        let mut percent_only_text = String::new();
        let percent_width = if self.show_percent {
            percent_text = format!(" {:3.0}%", value * 100.0);
            percent_only_text = percent_text.trim_start().to_owned();
            render_percent = true;
            display_width(&percent_text) as u16
        } else {
            0
        };

        if render_percent {
            if area.width <= percent_width {
                bar_width = 0;
            } else {
                let available = area.width - percent_width;
                bar_width = bar_width.min(available as usize);
            }
        }

        if bar_width == 0 {
            if render_percent {
                crate::draw_text_span(
                    frame,
                    area.x,
                    area.y,
                    &percent_only_text,
                    Style::default(),
                    area.right(),
                );
            }
            return;
        }

        let color = self.color_for_value_with_palette(value);
        let filled = self.filled_cells(bar_width);

        for i in 0..bar_width {
            let x = area.x + i as u16;
            if x >= area.right() {
                break;
            }
            let ch = if i < filled {
                self.filled_char
            } else {
                self.empty_char
            };
            let mut cell = Cell::from_char(ch);
            if deg.apply_styling() {
                apply_style(&mut cell, self.style);
                if i < filled {
                    cell.fg = color;
                }
            }
            frame.buffer.set_fast(x, area.y, cell);
        }

        if render_percent {
            let text_x = area.x + bar_width as u16;
            crate::draw_text_span(
                frame,
                text_x,
                area.y,
                &percent_text,
                Style::default(),
                area.right(),
            );
        }
    }
}

impl MeasurableWidget for MiniBar {
    fn measure(&self, _available: Size) -> SizeConstraints {
        // MiniBar has fixed dimensions
        let percent_width = if self.show_percent { 5 } else { 0 }; // " XXX%"
        let total_width = self.width.saturating_add(percent_width);

        SizeConstraints {
            min: Size::new(1, 1), // At least show something
            preferred: Size::new(total_width, 1),
            max: Some(Size::new(total_width, 1)), // Fixed size
        }
    }

    fn has_intrinsic_size(&self) -> bool {
        self.width > 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ftui_render::grapheme_pool::GraphemePool;

    fn cell_at(frame: &Frame, x: u16, y: u16) -> Cell {
        let cell = frame.buffer.get(x, y).copied();
        assert!(cell.is_some(), "test cell should exist at ({x},{y})");
        cell.unwrap()
    }

    fn raw_row_text(frame: &Frame, y: u16, width: u16) -> String {
        (0..width)
            .map(|x| {
                frame
                    .buffer
                    .get(x, y)
                    .and_then(|cell| cell.content.as_char())
                    .unwrap_or(' ')
            })
            .collect()
    }

    // ==================================================================
    // ProgressBarMode tests
    // ==================================================================

    #[test]
    fn mode_default_is_determinate() {
        assert_eq!(ProgressBarMode::default(), ProgressBarMode::Determinate);
    }

    #[test]
    fn mode_clone_and_eq() {
        let a = ProgressBarMode::Determinate;
        let b = ProgressBarMode::Indeterminate;
        assert_eq!(a, ProgressBarMode::Determinate);
        assert_ne!(a, b);
        let c = b.clone();
        assert_eq!(b, c);
    }

    // ==================================================================
    // Builder tests (existing + new)
    // ==================================================================

    #[test]
    fn default_progress_bar() {
        let pb = ProgressBar::new();
        assert_eq!(pb.ratio, 0.0);
        assert!(pb.label.is_none());
        assert!(pb.block.is_none());
        assert_eq!(pb.mode, ProgressBarMode::Determinate);
        assert!(!pb.auto_label);
        assert!(!pb.reduced_motion);
        assert!(pb.hit_id.is_none());
    }

    #[test]
    fn ratio_clamped_above_one() {
        let pb = ProgressBar::new().ratio(1.5);
        assert_eq!(pb.ratio, 1.0);
    }

    #[test]
    fn ratio_clamped_below_zero() {
        let pb = ProgressBar::new().ratio(-0.5);
        assert_eq!(pb.ratio, 0.0);
    }

    #[test]
    fn ratio_normal_range() {
        let pb = ProgressBar::new().ratio(0.5);
        assert!((pb.ratio - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn builder_label() {
        let pb = ProgressBar::new().label("50%");
        assert_eq!(pb.label, Some("50%"));
    }

    // --- New builder tests ---

    #[test]
    fn determinate_sets_ratio_and_auto_label() {
        let pb = ProgressBar::new().determinate(3, 5);
        assert_eq!(pb.mode, ProgressBarMode::Determinate);
        assert!((pb.ratio - 0.6).abs() < f64::EPSILON);
        assert!(pb.auto_label);
        assert_eq!(pb.current, Some(3));
        assert_eq!(pb.total, Some(5));
    }

    #[test]
    fn determinate_complete() {
        let pb = ProgressBar::new().determinate(100, 100);
        assert!((pb.ratio - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn determinate_zero() {
        let pb = ProgressBar::new().determinate(0, 10);
        assert!((pb.ratio - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    #[should_panic(expected = "total must be > 0")]
    fn determinate_zero_total_panics() {
        let _ = ProgressBar::new().determinate(5, 0);
    }

    #[test]
    fn indeterminate_sets_mode() {
        let pb = ProgressBar::new().indeterminate();
        assert_eq!(pb.mode, ProgressBarMode::Indeterminate);
    }

    #[test]
    fn indeterminate_marquee_offset() {
        let pb = ProgressBar::new().indeterminate().marquee_offset(7);
        assert_eq!(pb.marquee_offset, 7);
    }

    #[test]
    fn indeterminate_marquee_segment_width() {
        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_segment_width(5);
        assert_eq!(pb.marquee_segment_width, Some(5));
    }

    #[test]
    fn auto_label_enable_disable() {
        let pb = ProgressBar::new().auto_label(true);
        assert!(pb.auto_label);
        let pb = pb.auto_label(false);
        assert!(!pb.auto_label);
    }

    #[test]
    fn hit_id_builder() {
        let pb = ProgressBar::new().hit_id(HitId::new(42));
        assert_eq!(pb.hit_id, Some(HitId::new(42)));
    }

    #[test]
    fn show_pause_and_cancel() {
        let pb = ProgressBar::new().show_pause(true);
        assert!(pb.show_pause);
        assert!(!pb.show_cancel);
        let pb = pb.show_cancel(true);
        assert!(pb.show_cancel);
    }

    #[test]
    fn reduced_motion_builder() {
        let pb = ProgressBar::new().reduced_motion(true);
        assert!(pb.reduced_motion);
    }

    #[test]
    fn builder_chaining() {
        let pb = ProgressBar::new()
            .determinate(1, 4)
            .hit_id(HitId::new(1))
            .show_pause(true)
            .show_cancel(true)
            .reduced_motion(true)
            .marquee_offset(3)
            .marquee_segment_width(4)
            .style(Style::new().bold());
        assert_eq!(pb.mode, ProgressBarMode::Determinate);
        assert_eq!(pb.hit_id, Some(HitId::new(1)));
        assert!(pb.show_pause);
        assert!(pb.show_cancel);
        assert!(pb.reduced_motion);
    }

    // ==================================================================
    // Auto-label tests
    // ==================================================================

    #[test]
    fn auto_label_determinate_shows_fraction_and_pct() {
        let pb = ProgressBar::new().determinate(3, 5);
        assert_eq!(pb.effective_label(), Some("3/5 (60%)".to_owned()));
    }

    #[test]
    fn auto_label_determinate_no_current() {
        let pb = ProgressBar::new().auto_label(true).ratio(0.75);
        assert_eq!(pb.effective_label(), Some("75%".to_owned()));
    }

    #[test]
    fn auto_label_indeterminate_shows_ellipsis() {
        let pb = ProgressBar::new().indeterminate().auto_label(true);
        assert_eq!(pb.effective_label(), Some("...".to_owned()));
    }

    #[test]
    fn explicit_label_overrides_auto_label() {
        let pb = ProgressBar::new()
            .determinate(5, 10)
            .label("Custom");
        assert_eq!(pb.effective_label(), Some("Custom".to_owned()));
    }

    #[test]
    fn auto_label_disabled_no_label() {
        let pb = ProgressBar::new().determinate(3, 5).auto_label(false);
        assert_eq!(pb.effective_label(), None);
    }

    // ==================================================================
    // Determinate rendering tests (existing + new)
    // ==================================================================

    #[test]
    fn render_zero_area() {
        let pb = ProgressBar::new().ratio(0.5);
        let area = Rect::new(0, 0, 0, 0);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(1, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);
    }

    #[test]
    fn render_zero_ratio_no_fill() {
        let gauge_style = Style::new().bg(PackedRgba::RED);
        let pb = ProgressBar::new().ratio(0.0).gauge_style(gauge_style);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        for x in 0..10 {
            let cell = cell_at(&frame, x, 0);
            assert_ne!(
                cell.bg,
                PackedRgba::RED,
                "cell at x={x} should not have gauge bg"
            );
        }
    }

    #[test]
    fn render_full_ratio_fills_all() {
        let gauge_style = Style::new().bg(PackedRgba::GREEN);
        let pb = ProgressBar::new().ratio(1.0).gauge_style(gauge_style);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        for x in 0..10 {
            let cell = cell_at(&frame, x, 0);
            assert_eq!(
                cell.bg,
                PackedRgba::GREEN,
                "cell at x={x} should have gauge bg"
            );
        }
    }

    #[test]
    fn render_half_ratio() {
        let gauge_style = Style::new().bg(PackedRgba::BLUE);
        let pb = ProgressBar::new().ratio(0.5).gauge_style(gauge_style);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        let filled_count = (0..10)
            .filter(|&x| cell_at(&frame, x, 0).bg == PackedRgba::BLUE)
            .count();
        assert_eq!(filled_count, 5);
    }

    #[test]
    fn render_multi_row_bar() {
        let gauge_style = Style::new().bg(PackedRgba::RED);
        let pb = ProgressBar::new().ratio(1.0).gauge_style(gauge_style);
        let area = Rect::new(0, 0, 5, 3);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(5, 3, &mut pool);
        Widget::render(&pb, area, &mut frame);

        for y in 0..3 {
            for x in 0..5 {
                let cell = cell_at(&frame, x, y);
                assert_eq!(
                    cell.bg,
                    PackedRgba::RED,
                    "cell at ({x},{y}) should have gauge bg"
                );
            }
        }
    }

    #[test]
    fn render_with_label_centered() {
        let pb = ProgressBar::new().ratio(0.5).label("50%");
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        let c = frame.buffer.get(3, 0).and_then(|c| c.content.as_char());
        assert_eq!(c, Some('5'));
        let c = frame.buffer.get(4, 0).and_then(|c| c.content.as_char());
        assert_eq!(c, Some('0'));
        let c = frame.buffer.get(5, 0).and_then(|c| c.content.as_char());
        assert_eq!(c, Some('%'));
    }

    #[test]
    fn render_with_block() {
        let pb = ProgressBar::new()
            .ratio(1.0)
            .gauge_style(Style::new().bg(PackedRgba::GREEN))
            .block(Block::bordered());
        let area = Rect::new(0, 0, 10, 5);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 5, &mut pool);
        Widget::render(&pb, area, &mut frame);

        for x in 2..8 {
            let cell = cell_at(&frame, x, 2);
            assert_eq!(
                cell.bg,
                PackedRgba::GREEN,
                "inner cell at x={x} should have gauge bg"
            );
        }
    }

    // --- Determinate auto-label rendering ---

    #[test]
    fn determinate_render_shows_auto_label() {
        let pb = ProgressBar::new().determinate(3, 5);
        let area = Rect::new(0, 0, 20, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(20, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        let text = raw_row_text(&frame, 0, 20);
        assert!(text.contains("3/5 (60%)"), "auto-label missing: got {text:?}");
    }

    #[test]
    fn determinate_render_full_shows_100_pct() {
        let pb = ProgressBar::new().determinate(10, 10);
        let area = Rect::new(0, 0, 20, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(20, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        let text = raw_row_text(&frame, 0, 20);
        assert!(
            text.contains("10/10 (100%)"),
            "auto-label missing: got {text:?}"
        );
    }

    // ==================================================================
    // Indeterminate / marquee rendering tests
    // ==================================================================

    #[test]
    fn indeterminate_marquee_wraps() {
        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_offset(0)
            .marquee_segment_width(3)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        assert_eq!(cell_at(&frame, 0, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 1, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 2, 0).bg, PackedRgba::GREEN);
        assert_ne!(cell_at(&frame, 3, 0).bg, PackedRgba::GREEN);
    }

    #[test]
    fn indeterminate_marquee_offset_shifts() {
        let gauge = Style::new().bg(PackedRgba::BLUE);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);

        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_offset(3)
            .marquee_segment_width(3)
            .gauge_style(gauge);
        Widget::render(&pb, area, &mut frame);

        assert_ne!(cell_at(&frame, 0, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 3, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 4, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 5, 0).bg, PackedRgba::BLUE);
        assert_ne!(cell_at(&frame, 6, 0).bg, PackedRgba::BLUE);
    }

    #[test]
    fn indeterminate_marquee_wraps_around() {
        let gauge = Style::new().bg(PackedRgba::RED);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);

        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_offset(9)
            .marquee_segment_width(3)
            .gauge_style(gauge);
        Widget::render(&pb, area, &mut frame);

        assert_eq!(cell_at(&frame, 9, 0).bg, PackedRgba::RED);
        assert_eq!(cell_at(&frame, 0, 0).bg, PackedRgba::RED);
        assert_eq!(cell_at(&frame, 1, 0).bg, PackedRgba::RED);
        assert_ne!(cell_at(&frame, 2, 0).bg, PackedRgba::RED);
    }

    #[test]
    fn indeterminate_reduced_motion_centered() {
        let gauge = Style::new().bg(PackedRgba::GREEN);
        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_segment_width(4)
            .reduced_motion(true)
            .gauge_style(gauge);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        assert_ne!(cell_at(&frame, 0, 0).bg, PackedRgba::GREEN);
        assert_ne!(cell_at(&frame, 1, 0).bg, PackedRgba::GREEN);
        assert_ne!(cell_at(&frame, 2, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 3, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 4, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 5, 0).bg, PackedRgba::GREEN);
        assert_eq!(cell_at(&frame, 6, 0).bg, PackedRgba::GREEN);
        assert_ne!(cell_at(&frame, 7, 0).bg, PackedRgba::GREEN);
    }

    #[test]
    fn indeterminate_reduced_motion_ignores_offset() {
        let gauge = Style::new().bg(PackedRgba::BLUE);
        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_offset(99)
            .marquee_segment_width(4)
            .reduced_motion(true)
            .gauge_style(gauge);
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        Widget::render(&pb, area, &mut frame);

        assert_eq!(cell_at(&frame, 3, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 4, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 5, 0).bg, PackedRgba::BLUE);
        assert_eq!(cell_at(&frame, 6, 0).bg, PackedRgba::BLUE);
    }

    #[test]
    fn indeterminate_multi_row_marquee() {
        let gauge = Style::new().bg(PackedRgba::GREEN);
        let pb = ProgressBar::new()
            .indeterminate()
            .marquee_offset(0)
            .marquee_segment_width(3)
            .gauge_style(gauge);
        let area = Rect::new(0, 0, 10, 3);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 3, &mut pool);
        Widget::render(&pb, area, &mut frame);

        for y in 0..3 {
            assert_eq!(cell_at(&frame, 0, y).bg, PackedRgba::GREEN);
            assert_eq!(cell_at(&frame, 1, y).bg, PackedRgba::GREEN);
            assert_eq!(cell_at(&frame, 2, y).bg, PackedRgba::GREEN);
            assert_ne!(cell_at(&frame, 3, y).bg, PackedRgba::GREEN);
        }
    }

    // ==================================================================
    // EssentialOnly rendering (determinate + indeterminate)
    // ==================================================================

    #[test]
    fn degradation_essential_only_shows_auto_label() {
        use ftui_render::budget::DegradationLevel;

        let pb = ProgressBar::new()
            .determinate(3, 5)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        frame.buffer.degradation = DegradationLevel::EssentialOnly;
        Widget::render(&pb, area, &mut frame);

        let text = raw_row_text(&frame, 0, 10);
        assert!(
            text.contains("3/5"),
            "expected auto-label at EssentialOnly, got {text:?}"
        );
    }

    #[test]
    fn degradation_essential_only_indeterminate_shows_ellipsis() {
        use ftui_render::budget::DegradationLevel;

        let pb = ProgressBar::new()
            .indeterminate()
            .auto_label(true)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        frame.buffer.degradation = DegradationLevel::EssentialOnly;
        Widget::render(&pb, area, &mut frame);

        let text = raw_row_text(&frame, 0, 10);
        assert!(
            text.contains("..."),
            "expected '...' at EssentialOnly, got {text:?}"
        );
    }

    // ==================================================================
    // Hit region tests
    // ==================================================================

    #[test]
    fn render_with_hit_registers_pause_and_cancel() {
        let pb = ProgressBar::new()
            .ratio(0.5)
            .hit_id(HitId::new(99))
            .show_pause(true)
            .show_cancel(true);
        let area = Rect::new(0, 0, 20, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(20, 1, &mut pool);
        frame.enable_hit_testing();
        Widget::render(&pb, area, &mut frame);

        let hit = frame.hit_test(19, 0);
        assert_eq!(hit, Some((HitId::new(99), PROGRESS_HIT_CANCEL, 1)));

        let hit = frame.hit_test(17, 0);
        assert_eq!(hit, Some((HitId::new(99), PROGRESS_HIT_PAUSE, 0)));

        let hit = frame.hit_test(18, 0);
        assert_eq!(hit, Some((HitId::new(99), PROGRESS_HIT_PAUSE, 0)));
    }

    #[test]
    fn render_with_hit_no_pause_if_not_set() {
        let pb = ProgressBar::new()
            .ratio(0.5)
            .hit_id(HitId::new(99))
            .show_cancel(true);
        let area = Rect::new(0, 0, 20, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(20, 1, &mut pool);
        frame.enable_hit_testing();
        Widget::render(&pb, area, &mut frame);

        let hit = frame.hit_test(19, 0);
        assert_eq!(hit, Some((HitId::new(99), PROGRESS_HIT_CANCEL, 1)));

        let hit = frame.hit_test(17, 0);
        assert_ne!(hit.map(|h| h.1), Some(PROGRESS_HIT_PAUSE));
    }

    // ==================================================================
    // ProgressBarGroup tests
    // ==================================================================

    #[test]
    fn group_default() {
        let g = ProgressBarGroup::new();
        assert!(g.items.is_empty());
        assert_eq!(g.spacing, 0);
    }

    #[test]
    fn group_add_items() {
        let g = ProgressBarGroup::new()
            .add(ProgressBarGroupItem::new(
                "Task A",
                ProgressBar::new().determinate(3, 5),
            ))
            .add(ProgressBarGroupItem::new(
                "Task B",
                ProgressBar::new().indeterminate(),
            ));
        assert_eq!(g.items.len(), 2);
        assert_eq!(g.items[0].label, "Task A");
        assert_eq!(g.items[1].label, "Task B");
    }

    #[test]
    fn group_item_status() {
        let item = ProgressBarGroupItem::new("Test", ProgressBar::new()).status("Running");
        assert_eq!(item.status, Some("Running"));
    }

    #[test]
    fn group_render_zero_area() {
        let g = ProgressBarGroup::new().add(ProgressBarGroupItem::new(
            "A",
            ProgressBar::new().ratio(0.5),
        ));
        let area = Rect::new(0, 0, 0, 0);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 10, &mut pool);
        Widget::render(&g, area, &mut frame);
    }

    #[test]
    fn group_render_empty() {
        let g = ProgressBarGroup::new();
        let area = Rect::new(0, 0, 10, 10);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 10, &mut pool);
        Widget::render(&g, area, &mut frame);
    }

    #[test]
    fn group_spacing() {
        let g = ProgressBarGroup::new()
            .spacing(1)
            .add(ProgressBarGroupItem::new(
                "A",
                ProgressBar::new().ratio(0.5),
            ))
            .add(ProgressBarGroupItem::new(
                "B",
                ProgressBar::new().ratio(1.0),
            ));
        assert_eq!(g.spacing, 1);
    }

    // ==================================================================
    // Edge-case tests
    // ==================================================================

    #[test]
    fn ratio_nan_clamped_to_zero() {
        let pb = ProgressBar::new().ratio(f64::NAN);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        let area = Rect::new(0, 0, 10, 1);
        Widget::render(&pb, area, &mut frame);
    }

    #[test]
    fn ratio_infinity_clamped() {
        let pb = ProgressBar::new().ratio(f64::INFINITY);
        assert_eq!(pb.ratio, 1.0);

        let pb_neg = ProgressBar::new().ratio(f64::NEG_INFINITY);
        assert_eq!(pb_neg.ratio, 0.0);
    }

    #[test]
    fn label_wider_than_area() {
        let pb = ProgressBar::new()
            .ratio(0.5)
            .label("This is a very long label text");
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        let area = Rect::new(0, 0, 5, 1);
        Widget::render(&pb, area, &mut frame);
    }

    #[test]
    fn label_on_multi_row_bar_vertically_centered() {
        let pb = ProgressBar::new().ratio(0.5).label("X");
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 5, &mut pool);
        let area = Rect::new(0, 0, 10, 5);
        Widget::render(&pb, area, &mut frame);
        let c = frame.buffer.get(4, 2).and_then(|c| c.content.as_char());
        assert_eq!(c, Some('X'));
    }

    #[test]
    fn empty_label_renders_no_text() {
        let pb = ProgressBar::new().ratio(0.5).label("");
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        let area = Rect::new(0, 0, 10, 1);
        Widget::render(&pb, area, &mut frame);
    }

    #[test]
    fn progress_bar_clone_and_debug() {
        let pb = ProgressBar::new().ratio(0.5).label("test");
        let cloned = pb.clone();
        assert!((cloned.ratio - 0.5).abs() < f64::EPSILON);
        assert_eq!(cloned.label, Some("test"));
        let dbg = format!("{:?}", pb);
        assert!(dbg.contains("ProgressBar"));
    }

    #[test]
    fn progress_bar_default_trait() {
        let pb = ProgressBar::default();
        assert_eq!(pb.ratio, 0.0);
        assert!(pb.label.is_none());
    }

    #[test]
    fn render_width_one() {
        let pb = ProgressBar::new()
            .ratio(1.0)
            .gauge_style(Style::new().bg(PackedRgba::RED));
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(1, 1, &mut pool);
        let area = Rect::new(0, 0, 1, 1);
        Widget::render(&pb, area, &mut frame);
        assert_eq!(cell_at(&frame, 0, 0).bg, PackedRgba::RED);
    }

    #[test]
    fn render_ratio_just_above_zero() {
        let pb = ProgressBar::new()
            .ratio(0.01)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(100, 1, &mut pool);
        let area = Rect::new(0, 0, 100, 1);
        Widget::render(&pb, area, &mut frame);
        assert_eq!(cell_at(&frame, 0, 0).bg, PackedRgba::GREEN);
        assert_ne!(cell_at(&frame, 1, 0).bg, PackedRgba::GREEN);
    }

    // --- Degradation tests (existing) ---

    #[test]
    fn degradation_skeleton_skips_entirely() {
        use ftui_render::budget::DegradationLevel;

        let pb = ProgressBar::new()
            .ratio(0.5)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        frame.buffer.degradation = DegradationLevel::Skeleton;
        Widget::render(&pb, area, &mut frame);

        for x in 0..10 {
            assert!(
                cell_at(&frame, x, 0).is_empty(),
                "cell at x={x} should be empty at Skeleton"
            );
        }
    }

    #[test]
    fn degradation_essential_only_renders_pct_text() {
        use ftui_render::budget::DegradationLevel;

        let pb = ProgressBar::new()
            .ratio(0.5)
            .gauge_style(Style::new().bg(PackedRgba::GREEN));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        frame.buffer.degradation = DegradationLevel::EssentialOnly;
        Widget::render(&pb, area, &mut frame);

        assert_eq!(cell_at(&frame, 0, 0).content.as_char(), Some('5'));
        assert_eq!(cell_at(&frame, 1, 0).content.as_char(), Some('0'));
        assert_eq!(cell_at(&frame, 2, 0).content.as_char(), Some('%'));
        assert_ne!(cell_at(&frame, 0, 0).bg, PackedRgba::GREEN);
    }

    #[test]
    fn degradation_full_renders_bar() {
        use ftui_render::budget::DegradationLevel;

        let pb = ProgressBar::new()
            .ratio(1.0)
            .gauge_style(Style::new().bg(PackedRgba::BLUE));
        let area = Rect::new(0, 0, 10, 1);
        let mut pool = GraphemePool::new();
        let mut frame = Frame::new(10, 1, &mut pool);
        frame.buffer.degradation = DegradationLevel::Full;
        Widget::render(&pb, area, &mut frame);

        for x in 0..10 {
            assert_eq!(
                cell_at(&frame, x, 0).bg,
                PackedRgba::BLUE,
                "cell at x={x} should have gauge bg at Full"
            );
        }
    }

    // ==================================================================
    // MiniBar tests (unchanged)
    // ==================================================================

    #[test]
    fn minibar_zero_is_empty() {
        let bar = MiniBar::new(0.0, 10);
        let filled = bar.render_string().chars().filter(|c| *c == '█').count();
        assert_eq!(filled, 0);
    }

    #[test]
    fn minibar_full_is_complete() {
        let bar = MiniBar::new(1.0, 10);
        let filled = bar.render_string().chars().filter(|c| *c == '█').count();
        assert_eq!(filled, 10);
    }

    #[test]
    fn minibar_half_is_half() {
        let bar = MiniBar::new(0.5, 10);
        let filled = bar.render_string().chars().filter(|c| *c == '█').count();
        assert!((4..=6).contains(&filled));
    }

    #[test]
    fn minibar_color_thresholds() {
        let high = MiniBar::color_for_value(0.80);
        let mid = MiniBar::color_for_value(0.60);
        let low = MiniBar::color_for_value(0.30);
        let crit = MiniBar::color_for_value(0.10);
        assert_ne!(high, mid);
        assert_ne!(mid, low);
        assert_ne!(low, crit);
    }

    #[test]
    fn minibar_respects_width() {
        for width in [5, 10, 20] {
            let bar = MiniBar::new(0.5, width);
            assert_eq!(bar.render_string().chars().count(), width as usize);
        }
    }

    // --- MeasurableWidget tests ---

    #[test]
    fn progress_bar_measure_has_intrinsic_size() {
        let pb = ProgressBar::new();
        assert!(pb.has_intrinsic_size());
    }

    #[test]
    fn progress_bar_measure_min_size() {
        let pb = ProgressBar::new();
        let c = pb.measure(Size::MAX);

        assert_eq!(c.min.width, 1);
        assert_eq!(c.min.height, 1);
        assert!(c.max.is_none());
    }

    #[test]
    fn progress_bar_measure_with_block() {
        let pb = ProgressBar::new().block(Block::bordered());
        let c = pb.measure(Size::MAX);

        assert_eq!(c.min.width, 5);
        assert_eq!(c.min.height, 5);
    }

    #[test]
    fn minibar_measure_fixed_width() {
        let bar = MiniBar::new(0.5, 10);
        let c = bar.measure(Size::MAX);

        assert_eq!(c.preferred.width, 10);
        assert_eq!(c.preferred.height, 1);
        assert_eq!(c.max, Some(Size::new(10, 1)));
    }

    #[test]
    fn minibar_measure_with_percent() {
        let bar = MiniBar::new(0.5, 10).show_percent(true);
        let c = bar.measure(Size::MAX);

        assert_eq!(c.preferred.width, 15);
        assert_eq!(c.preferred.height, 1);
    }

    #[test]
    fn minibar_measure_has_intrinsic_size() {
        let bar = MiniBar::new(0.5, 10);
        assert!(bar.has_intrinsic_size());

        let zero_width = MiniBar::new(0.5, 0);
        assert!(!zero_width.has_intrinsic_size());
    }
}
